"""Pet registry. One pet module is resident at a time (RAM is scarce on the M4).

Each pet module exposes NAME (str), BODY (0xRRGGBB int), and STATES: a dict keyed
by state name -> {"div": int, "seq": tuple[int], "poses": tuple[tuple[str x5]]}.
Modules are auto-generated by tools/port_buddies.py from the upstream species.
"""

# Curated order; UP/DOWN cycles through this list. Extend by porting more species
# (tools/port_buddies.py <name>) and appending the name here.
REGISTRY = ("cat", "duck", "robot", "ghost", "axolotl", "capybara")


def count():
    return len(REGISTRY)


def name_at(index):
    return REGISTRY[index % len(REGISTRY)]


def load(index):
    """Import and return the pet module at the given registry index (lazy)."""
    name = name_at(index)
    module = __import__("pets." + name, None, None, (name,))
    return getattr(module, name) if hasattr(module, name) else module
