#!/usr/bin/env python3
"""Generate device/pets/<name>.py from claude-desktop-buddy species sources.

The upstream project (Anthropic, MIT-licensed claude-desktop-buddy) defines each
desk-pet species as a C++ file under src/buddies/<name>.cpp. Every species has the
same shape: 7 state functions (doSleep/doIdle/doBusy/doAttention/doCelebrate/
doDizzy/doHeart), and within each, a set of named 5-row x 12-col ASCII poses, a
`P[]` array ordering them, a `SEQ[]` beat list indexing into P, and a
`beat = (t / DIV)` divisor controlling animation speed.

This is a one-time, host-side generator. It extracts the pose/sequence data (the
parts that port to our 64x32 LED panel) and emits a tiny pure-data Python module
per pet. Decorative particle overlays (z's, confetti, stars) are NOT parsed here;
buddy.py renders generic per-state effects instead.

Usage:
    python3 tools/port_buddies.py                      # all *.cpp in tools/buddy_src/
    python3 tools/port_buddies.py cat duck             # selected species
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
SRC_DIR = HERE / "buddy_src"
OUT_DIR = HERE.parent / "device" / "pets"

# C++ function name (without "do") -> our state key, in declaration order.
STATE_ORDER = [
    ("Sleep", "sleep"),
    ("Idle", "idle"),
    ("Busy", "busy"),
    ("Attention", "attention"),
    ("Celebrate", "celebrate"),
    ("Dizzy", "dizzy"),
    ("Heart", "heart"),
]

_SPECIES_RE = re.compile(
    r'Species\s+\w+_SPECIES\s*=\s*\{\s*"(\w+)"\s*,\s*0x([0-9A-Fa-f]{4})', re.DOTALL
)
_POSE_RE = re.compile(
    r'const\s+char\*\s+const\s+(\w+)\[5\]\s*=\s*\{(.*?)\};', re.DOTALL
)
_PARRAY_RE = re.compile(r'const\s+char\*\s+const\*\s+P\[\d+\]\s*=\s*\{([^}]*)\};')
_SEQ_RE = re.compile(r'const\s+uint8_t\s+SEQ\[\]\s*=\s*\{([^}]*)\};', re.DOTALL)
_DIV_RE = re.compile(r'beat\s*=\s*\(t\s*/\s*(\d+)\)')
_STR_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def rgb565_to_888(v: int) -> int:
    r5, g6, b5 = (v >> 11) & 0x1F, (v >> 5) & 0x3F, v & 0x1F
    r = (r5 << 3) | (r5 >> 2)
    g = (g6 << 2) | (g6 >> 4)
    b = (b5 << 3) | (b5 >> 2)
    return (r << 16) | (g << 8) | b


def _unescape(s: str) -> str:
    # Only \" and \\ appear in the upstream pose strings.
    return s.replace('\\"', '"').replace('\\\\', '\\')


def _parse_strings(block: str) -> list[str]:
    return [_unescape(m.group(1)) for m in _STR_RE.finditer(block)]


def _state_bodies(text: str) -> dict[str, str]:
    """Slice each `static void do<Name>(uint32_t t) { ... }` body out of the file."""
    bodies: dict[str, str] = {}
    starts = [(m.group(1), m.start()) for m in re.finditer(r'void\s+do(\w+)\(uint32_t t\)', text)]
    for i, (name, pos) in enumerate(starts):
        end = starts[i + 1][1] if i + 1 < len(starts) else text.find('}  // namespace', pos)
        if end == -1:
            end = len(text)
        bodies[name] = text[pos:end]
    return bodies


def parse_species(text: str) -> tuple[str, int, dict]:
    sm = _SPECIES_RE.search(text)
    if not sm:
        raise ValueError("no Species declaration found")
    name, body_color = sm.group(1), rgb565_to_888(int(sm.group(2), 16))

    bodies = _state_bodies(text)
    states: dict[str, dict] = {}
    for cpp_name, key in STATE_ORDER:
        body = bodies.get(cpp_name)
        if body is None:
            raise ValueError("missing do{} in {}".format(cpp_name, name))

        pose_map = {m.group(1): _parse_strings(m.group(2)) for m in _POSE_RE.finditer(body)}
        for pose_name, lines in pose_map.items():
            if len(lines) != 5:
                raise ValueError("{}.{}: pose {} has {} rows".format(name, key, pose_name, len(lines)))

        pm = _PARRAY_RE.search(body)
        if not pm:
            raise ValueError("{}.{}: no P[] array".format(name, key))
        p_names = [n.strip() for n in pm.group(1).split(',') if n.strip()]
        poses = [pose_map[n] for n in p_names]

        seqm = _SEQ_RE.search(body)
        seq = [int(x) for x in seqm.group(1).replace('\n', ' ').split(',') if x.strip()]

        divm = _DIV_RE.search(body)
        div = int(divm.group(1)) if divm else 5

        states[key] = {"div": div, "seq": seq, "poses": poses}
    return name, body_color, states


def emit(name: str, body_color: int, states: dict) -> str:
    out = [
        "# Auto-generated by tools/port_buddies.py - do not edit by hand.",
        "# Ported from Anthropic claude-desktop-buddy (MIT), src/buddies/{}.cpp".format(name),
        "# Poses are 5 rows x 12 cols of ASCII; SEQ indexes POSES; DIV sets beat speed.",
        "",
        'NAME = "{}"'.format(name),
        "BODY = 0x{:06X}".format(body_color),
        "",
        "STATES = {",
    ]
    for _cpp, key in STATE_ORDER:
        st = states[key]
        out.append('    "{}": {{'.format(key))
        out.append('        "div": {},'.format(st["div"]))
        out.append('        "seq": {},'.format(tuple(st["seq"])))
        out.append('        "poses": (')
        for pose in st["poses"]:
            joined = ", ".join('"{}"'.format(line.replace('\\', '\\\\').replace('"', '\\"')) for line in pose)
            out.append('            ({},),'.format(joined))
        out.append("        ),")
        out.append("    },")
    out.append("}")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    names = argv or [p.stem for p in sorted(SRC_DIR.glob("*.cpp"))]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for n in names:
        src = SRC_DIR / "{}.cpp".format(n)
        if not src.exists():
            print("skip {}: {} missing".format(n, src))
            continue
        name, color, states = parse_species(src.read_text())
        dest = OUT_DIR / "{}.py".format(name)
        dest.write_text(emit(name, color, states))
        n_poses = sum(len(s["poses"]) for s in states.values())
        print("wrote {}  body=0x{:06X}  {} poses across {} states".format(dest, color, n_poses, len(states)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
